services:
  server:
    container_name: app
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db


  db:
    container_name: db
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - db


volumes:
  postgres_data: